export const sampleQuestions = [
  {
    question: "What is the speed of light?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "How many bones are there in human body?",
    subject: "Biology",
    topic: "Human Body",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who was first female president of India?",
    subject: "GK",
    topic: "Politics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which is the smallest planet in size?",
    subject: "Physics",
    topic: "Space",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which planet is known as evening star?",
    subject: "Physics",
    topic: "Space",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Explain Pythagauras Theorem.",
    subject: "Maths",
    topic: "Triangles",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the sum of all angles of a triangle?",
    subject: "Maths",
    topic: "Triangles",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Where is Bharam Sarovar situated?",
    subject: "GK",
    topic: "Places",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Fishes respirate through which organ?",
    subject: "Biology",
    topic: "Animals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Define Newton's first law of motion.",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the largest planet in our solar system.",
    subject: "Astronomy",
    topic: "Planets",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the capital of France?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: 'Who wrote "Romeo and Juliet"?',
    subject: "Literature",
    topic: "Shakespeare",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the chemical symbol for gold?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Solve 2 + 3 * 4",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the largest mammal on Earth?",
    subject: "Biology",
    topic: "Mammals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "In which year did World War I begin?",
    subject: "History",
    topic: "World War I",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the process by which plants make their own food.",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who painted the Mona Lisa?",
    subject: "Art",
    topic: "Paintings",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the powerhouse of the cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the boiling point of water in Celsius?",
    subject: "Chemistry",
    topic: "States of Matter",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: 'Who is known as the "Father of Computer Science"?',
    subject: "Computer Science",
    topic: "Pioneers",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the currency of Japan?",
    subject: "Economics",
    topic: "Currencies",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the process by which plants lose water vapor.",
    subject: "Biology",
    topic: "Transpiration",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who discovered penicillin?",
    subject: "Medicine",
    topic: "Antibiotics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the longest river in the world?",
    subject: "Geography",
    topic: "Rivers",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: 'Who wrote "To Kill a Mockingbird"?',
    subject: "Literature",
    topic: "Novels",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the chemical formula for water?",
    subject: "Chemistry",
    topic: "Compounds",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who is the current president of the United States?",
    subject: "Politics",
    topic: "World Leaders",
    difficulty: "Medium",
    marks: 5,
  },
];
