export const questions = [
  {
    question: "What is the speed of light?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "How many bones are there in human body?",
    subject: "Biology",
    topic: "Human Body",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who was first female president of India?",
    subject: "GK",
    topic: "Politics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which is the smallest planet in size?",
    subject: "Physics",
    topic: "Space",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which planet is known as evening star?",
    subject: "Physics",
    topic: "Space",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Explain Pythagauras Theorem.",
    subject: "Maths",
    topic: "Triangles",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the sum of all angles of a triangle?",
    subject: "Maths",
    topic: "Triangles",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Where is Bharam Sarovar situated?",
    subject: "GK",
    topic: "Places",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Fishes respirate through which organ?",
    subject: "Biology",
    topic: "Animals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Define Newton's first law of motion.",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the largest planet in our solar system.",
    subject: "Astronomy",
    topic: "Planets",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the capital of France?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: 'Who wrote "Romeo and Juliet"?',
    subject: "Literature",
    topic: "Shakespeare",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the chemical symbol for gold?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Solve 2 + 3 * 4",
    subject: "Mathematics",
    topic: "Arithmetic",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the largest mammal on Earth?",
    subject: "Biology",
    topic: "Mammals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "In which year did World War I begin?",
    subject: "History",
    topic: "World War I",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the process by which plants make their own food.",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who painted the Mona Lisa?",
    subject: "Art",
    topic: "Paintings",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the powerhouse of the cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the boiling point of water in Celsius?",
    subject: "Chemistry",
    topic: "States of Matter",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: 'Who is known as the "Father of Computer Science"?',
    subject: "Computer Science",
    topic: "Pioneers",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the currency of Japan?",
    subject: "Economics",
    topic: "Currencies",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Name the process by which plants lose water vapor.",
    subject: "Biology",
    topic: "Transpiration",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who discovered penicillin?",
    subject: "Medicine",
    topic: "Antibiotics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the longest river in the world?",
    subject: "Geography",
    topic: "Rivers",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: 'Who wrote "To Kill a Mockingbird"?',
    subject: "Literature",
    topic: "Novels",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the chemical formula for water?",
    subject: "Chemistry",
    topic: "Compounds",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who is the current president of the United States?",
    subject: "Politics",
    topic: "World Leaders",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the powerhouse of the cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who discovered the theory of relativity?",
    subject: "Physics",
    topic: "Quantum Physics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "In which year did World War II end?",
    subject: "History",
    topic: "World War II",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the capital of Brazil?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the largest ocean on Earth.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Who wrote the play 'Romeo and Juliet'?",
    subject: "Literature",
    topic: "Shakespeare",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the chemical formula for table salt?",
    subject: "Chemistry",
    topic: "Chemical Compounds",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which country is known as the Land of the Rising Sun?",
    subject: "Geography",
    topic: "Countries",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the largest desert in the world?",
    subject: "Geography",
    topic: "Deserts",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who painted the Mona Lisa?",
    subject: "Art",
    topic: "Paintings",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the speed of sound in air?",
    subject: "Physics",
    topic: "Acoustics",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the process by which plants make their own food.",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Which gas is most abundant in the Earth's atmosphere?",
    subject: "Chemistry",
    topic: "Atmosphere",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Who developed the theory of evolution by natural selection?",
    subject: "Biology",
    topic: "Evolution",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the currency of Japan?",
    subject: "Economics",
    topic: "Currencies",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Name the process by which water changes from a liquid to a gas.",
    subject: "Physics",
    topic: "States of Matter",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Who invented the telephone?",
    subject: "Inventions",
    topic: "Communication",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the largest mountain in the world?",
    subject: "Geography",
    topic: "Mountains",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who wrote 'To Kill a Mockingbird'?",
    subject: "Literature",
    topic: "Novels",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the capital of South Africa?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Who is known as the 'Father of Computer Science'?",
    subject: "Computer Science",
    topic: "Pioneers",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Which planet is known as the Red Planet?",
    subject: "Astronomy",
    topic: "Planets",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the largest mammal on Earth?",
    subject: "Biology",
    topic: "Mammals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "In which year did the Titanic sink?",
    subject: "History",
    topic: "Maritime History",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who is the author of '1984'?",
    subject: "Literature",
    topic: "Novels",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the chemical symbol for gold?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Who discovered penicillin?",
    subject: "Medicine",
    topic: "Antibiotics",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the boiling point of water in Celsius?",
    subject: "Chemistry",
    topic: "States of Matter",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which river is the longest in the world?",
    subject: "Geography",
    topic: "Rivers",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Who painted 'Starry Night'?",
    subject: "Art",
    topic: "Paintings",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the capital of Australia?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Who discovered the electron?",
    subject: "Physics",
    topic: "Particle Physics",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which gas do plants absorb during photosynthesis?",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the melting point of ice in Fahrenheit?",
    subject: "Chemistry",
    topic: "States of Matter",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Who wrote 'Pride and Prejudice'?",
    subject: "Literature",
    topic: "Novels",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the currency of China?",
    subject: "Economics",
    topic: "Currencies",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Which gas is responsible for the greenhouse effect?",
    subject: "Environmental Science",
    topic: "Climate Change",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Who developed the theory of relativity?",
    subject: "Physics",
    topic: "Quantum Physics",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the capital of France?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who is known as the 'Father of Genetics'?",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Which element has the symbol 'O'?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "In which year did the Berlin Wall fall?",
    subject: "History",
    topic: "Cold War",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who painted 'The Last Supper'?",
    subject: "Art",
    topic: "Paintings",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the capital of Canada?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Who is known as the 'Father of Modern Physics'?",
    subject: "Physics",
    topic: "Pioneers",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Which planet is known as the 'Morning Star'?",
    subject: "Astronomy",
    topic: "Planets",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "What is the smallest prime number?",
    subject: "Mathematics",
    topic: "Number Theory",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Who wrote 'The Great Gatsby'?",
    subject: "Literature",
    topic: "Novels",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the capital of Russia?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Hard",
    marks: 5,
  },
  {
    question: "Who discovered the laws of planetary motion?",
    subject: "Astronomy",
    topic: "Planets",
    difficulty: "Medium",
    marks: 5,
  },
];
